// Pre-renders the two base maps into js/geo.js so the site ships with no runtime map dependencies.
// Run with: npm run build:geo
import { readFileSync, writeFileSync } from "node:fs";
import { geoEqualEarth, geoEquirectangular, geoPath } from "d3-geo";
import { feature, mesh } from "topojson-client";

const read = (name) => JSON.parse(readFileSync(new URL(`../node_modules/world-atlas/${name}`, import.meta.url)));
const round = (d) => d.replace(/-?\d+\.\d+/g, (n) => (+n).toFixed(1));

// World: Pacific-centred Equal Earth, cut in the mid-Atlantic (25°W) so no continent is split.
const WORLD = { w: 1200, h: 560, center: 155 };
const c110 = read("countries-110m.json");
const land110 = feature(c110, c110.objects.land);
const borders110 = mesh(c110, c110.objects.countries, (a, b) => a !== b);
const worldProj = geoEqualEarth().rotate([-WORLD.center, 0]).fitExtent([[6, 6], [WORLD.w - 6, WORLD.h - 6]], {
  type: "Feature",
  geometry: { type: "MultiPoint", coordinates: [[-24.9, 0], [-25.1, 0], [155, 80], [155, -56]] },
});
const worldPath = geoPath(worldProj.clipExtent([[0, 0], [WORLD.w, WORLD.h]]));
const [tx, ty] = worldProj.translate();

// Tropical Pacific: plain equirectangular, 110°E → 70°W, 35°S → 35°N.
const PAC = { w: 1080, h: 420, lon0: 110, lon1: 290, lat0: -35, lat1: 35 };
const l50 = read("land-50m.json");
const land50 = feature(l50, l50.objects.land);
const pacProj = geoEquirectangular()
  .rotate([-(PAC.lon0 + PAC.lon1) / 2, 0])
  .scale(PAC.w / Math.PI)
  .translate([PAC.w / 2, PAC.h / 2])
  .clipExtent([[0, 0], [PAC.w, PAC.h]]);
const pacPath = geoPath(pacProj);

const out = {
  world: {
    w: WORLD.w, h: WORLD.h, center: WORLD.center, k: worldProj.scale(), tx, ty,
    land: round(worldPath(land110)),
    borders: round(worldPath(borders110)),
    sphere: round(worldPath({ type: "Sphere" })),
  },
  pacific: { ...PAC, land: round(pacPath(land50)) },
};

writeFileSync(new URL("../js/geo.js", import.meta.url), `// Generated by scripts/build-geo.mjs — do not edit.\nwindow.GEO = ${JSON.stringify(out)};\n`);
console.log("world land", out.world.land.length, "borders", out.world.borders.length, "pacific", out.pacific.land.length);
console.log("scale", out.world.k, "translate", tx, ty);
// Sanity: where do a few known points land?
for (const [name, p] of Object.entries({ jakarta: [106.8, -6.2], lima: [-77, -12], nino34: [-145, 0], london: [0, 51.5], dakar: [-17.4, 14.7] })) {
  console.log(name, worldProj(p).map((v) => v.toFixed(0)).join(","));
}
